[api_bcra]
api_key = eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NDA1NDA4MjUsInR5cGUiOiJleHRlcm5hbCIsInVzZXIiOiJjcmlzdGlhbmNhbGlxdWlzQHlhaG9vLmNvbS5hciJ9.BVIuJSEPz5x-DuD5VNQaGJ9u82EOuf7zyzQTarAP3OL6wfmLtzUe1U38xWtA3FfpeTOkd5h_HpeWCFUFDv7ocw

[redshift]
host = data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com
port = 5439
username = cristiancaliquis_coderhouse
pwd = T93hbU4sqc
dbname = data-engineer-database
schema = cristiancaliquis_coderhouse
